theme: jekyll-theme-midnight
title: "Jeff Spinner Portfolio"
description: "A portfolio showcasing my personal and professional work."
baseurl: "" # Leave empty for GitHub Pages
url: "https://spinnerj.github.io"
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

navigation:
  - name: "Home"
    link: "/"
  - name: "Personal"
    link: "/personal/"
  - name: "Professional"
    link: "/professional/"
